# Rockchip RK3399 hexa core 4GB RAM SoC GBE eMMC USB3 USB-C
BOARD_NAME="Rockchip Sapphire"
BOARDFAMILY="rockchip64" # Used to be rk3399
BOARD_MAINTAINER="test"
BOOTCONFIG="rk-sapphire-rk3399_defconfig"
KERNEL_TARGET="current,edge,vendor"
KERNEL_TEST_TARGET="current"
FULL_DESKTOP="yes"
ASOUND_STATE="asound.state.rt5651"
BOOT_LOGO="desktop"
PACKAGE_LIST_BOARD="bash-completion net-tools vim"

function post_family_tweaks__rk-sapphire() {
	display_alert "$BOARD" "Installing board tweaks" "info"

	return 0
}
function post_family_tweaks_bsp__rk-sapphire() {
	display_alert "$BOARD" "Installing BSP firmware and fixups" "info"

	return 0
}

function post_family_config_branch_vendor__use_3rd_kernel() {
	display_alert "$BOARD" "Using vendor kernel" "info"

	declare -g KERNEL_MAJOR_MINOR="6.1" # Major and minor versions of this kernel.

	declare -g KERNELSOURCE='https://github.com/unifreq/linux-6.1.y.git'
	declare -g KERNELBRANCH='branch:main'
	declare -g KERNELPATCHDIR='unifreq-linux-6.1'

	declare -g EXTRAWIFI="no"

	return 0
}
